services:

  # Next.js Service
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - fastapp
  
  # Flask Service
  fastapp:
    container_name: fastapp
    image: fastapp:1.0.0
    build:
      context: ./backend
      dockerfile: fast.dockerfile
    ports:
      - 4000:4000
    env_file:
      - ./.env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}