name: personal-homepage-dev
channels:
  - conda-forge
dependencies:
  - annotated-types=0.7.0
  - anyio=4.4.0
  - black=24.4.2
  - build=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - click=8.1.7
  - colorama=0.4.6
  - coverage=7.5.3
  - cryptography=41.0.7
  - deprecation=2.1.0
  - dnspython=2.6.1
  - email-validator=2.1.1
  - email_validator=2.1.1
  - exceptiongroup=1.2.0
  - fastapi=0.111.0
  - fastapi-cli=0.0.4
  - flake8=7.0.0
  - gotrue=2.4.4
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.25.2
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=7.1.0
  - iniconfig=2.0.0
  - jinja2=3.1.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=17.0.6
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsqlite=3.45.3
  - libzlib=1.3.1
  - llvm-openmp=18.1.7
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.3.1
  - orjson=3.10.3
  - packaging=24.0
  - pandas=2.2.2
  - pathspec=0.12.1
  - pep517=0.13.0
  - pip=24.0
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - postgrest=0.16.8
  - pycodestyle=2.11.1
  - pycparser=2.22
  - pydantic=2.7.3
  - pydantic-core=2.18.4
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pytest=8.2.2
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-multipart=0.0.9
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - readline=8.2
  - realtime=1.0.5
  - rich=13.7.1
  - setuptools=70.0.0
  - shellingham=1.5.4
  - six=1.16.0
  - sniffio=1.3.1
  - starlette=0.37.2
  - storage3=0.7.6
  - strenum=0.4.15
  - supabase=2.5.0
  - supafunc=0.4.6
  - tk=8.6.13
  - tomli=2.0.1
  - typer=0.12.3
  - typer-slim=0.12.3
  - typer-slim-standard=0.12.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ujson=5.10.0
  - uvicorn=0.30.1
  - websockets=12.0
  - wheel=0.43.0
  - xz=5.2.6
  - zipp=3.18.0